### ISSUE TITLE
Anfrage für Erstellung einer einfachen "Responsive Website"

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [GodRamses/gitproject#2]
@GodRamses: Webseite erstellen?

**Comment by SuriyaaKudoIsc** [comment]
@GodRamses: Warum hab ich heute nicht geduscht?

**Comment by GodRamses** [comment]
@SuriyaaKudoIsc 'Scheiße in die Luft geschossen, gibt mächtig viele Sommersproßen.

**Comment by SuriyaaKudoIsc** [comment]
:satisfied:

**Comment by GodRamses** [comment]
:satisfied:

**Comment by SuriyaaKudoIsc** [comment]
:+1:

**Comment by GodRamses** [comment]
Alsooo mein Plan wäre das wir für mich eine Internetseite programmieren die wir dann nach und nach verbessern. Was halten sie von dieser werten Idee mein Herr??

**Comment by SuriyaaKudoIsc** [comment]
:hankey: LOL!

**Comment by SuriyaaKudoIsc** [comment]
Ok. :+1:

**Comment by SuriyaaKudoIsc** [comment]
Hab dich als Mitentwickler hinzugefügt: https://github.com/iSC-Host/alexbouton.tk!

**Comment by GodRamses** [comment]
Ok, sind das alles Projekte von dir ??
